name: Build and Deploy Vue Application
on:
  push:
    branches:
      - "main"
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: thefrustrateddev/vue-deploy-github-pages@v1.0.0
        with:
          username: "ikroeber"
          reponame: "ikroeber.github.io"
          email: "igor.kroeber@protonmail.com"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: actions/upload-pages-artifact@v1.0.3
        with:
          path: "./"
