name: Build and Deploy Vue Application
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Vue Application
    steps:
      - uses: actions/checkout@v2
      - uses: thefrustrateddev/vue-deploy-github-pages@v1.0.0
        with:
          username: "ikroeber"
          reponame: "ikroeber.github.io"
          email: "igor.kroeber@gmail.com"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: actions/upload-pages-artifact@v1.0.3
        with:
          path: "./"

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    name: Deploy to Github Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1.0.9
